export default {
  BASE_URL: 'https://divinity.milklegend.xyz',
  HOME: '/',
  ABOUT: '/about',
  FAQ: '/faq',
  BLOCKED: '/blocked',
  MAINTENANCE: '/maintenance',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  TOS: '/terms-of-service',
  DASHBOARD: '/myaccount/dashboard',
  TRANSACTIONS: '/myaccount/transactions',
  LOANS: '/myaccount/loans',
  SETTINGS: '/myaccount/settings',
};
