export default {
  HOME: '/',
  ABOUT: '/about',
  FAQ: '/faq',
  BLOCKED: '/blocked',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  TOS: '/terms-of-service',
  DASHBOARD: '/myaccount/dashboard',
  DEPOSIT: '/myaccount/deposit',
  WITHDRAW: '/myaccount/withdraw',
  TRANSACTIONS: '/myaccount/transactions',
  TRANSFER: '/myaccount/transfer',
  LOANS: '/myaccount/loans',
  SETTINGS: '/myaccount/settings',
};
