name: 🚀 Deploy (production)
on:
  push:
    branches:
      - release/production
    paths-ignore:
      - ".vscode/**"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PRODUCTION }}

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/release/production' }}
        run: flyctl deploy --remote-only --config ./fly.production.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PRODUCTION }}
